# Generated by Django 5.2 on 2026-01-11 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên persona")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="personas/avatars/",
                        verbose_name="Ảnh đại diện",
                    ),
                ),
                ("description", models.TextField(verbose_name="Mô tả")),
                (
                    "personality_type",
                    models.CharField(
                        choices=[
                            ("friendly", "Thân thiện"),
                            ("strict", "Nghiêm khắc"),
                            ("anxious", "Lo lắng"),
                            ("demanding", "Đòi hỏi cao"),
                            ("supportive", "Hỗ trợ"),
                            ("skeptical", "Hoài nghi"),
                            ("busy", "Bận rộn"),
                        ],
                        default="friendly",
                        max_length=20,
                        verbose_name="Kiểu tính cách",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Dễ"),
                            ("medium", "Trung bình"),
                            ("hard", "Khó"),
                            ("expert", "Chuyên gia"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Mức độ khó",
                    ),
                ),
                (
                    "background",
                    models.TextField(
                        blank=True,
                        help_text="Hoàn cảnh gia đình, nghề nghiệp, mối quan tâm của phụ huynh",
                        verbose_name="Câu chuyện nền",
                    ),
                ),
                (
                    "child_name",
                    models.CharField(
                        blank=True,
                        help_text="Tên của học sinh/con trong kịch bản",
                        max_length=100,
                        verbose_name="Tên con",
                    ),
                ),
                (
                    "child_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tuổi con"
                    ),
                ),
                (
                    "child_grade",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Lớp/Khối"
                    ),
                ),
                (
                    "communication_style",
                    models.TextField(
                        blank=True,
                        help_text="Cách nói chuyện, từ ngữ thường dùng, thái độ",
                        verbose_name="Phong cách giao tiếp",
                    ),
                ),
                (
                    "common_concerns",
                    models.TextField(
                        blank=True,
                        help_text="Các vấn đề phụ huynh thường hỏi hoặc lo lắng",
                        verbose_name="Mối quan tâm thường gặp",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Prompt gửi cho AI để đóng vai persona này",
                        verbose_name="System Prompt",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_personas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Tự động tạo từ nội dung hội thoại nếu để trống",
                        max_length=255,
                        verbose_name="Tiêu đề",
                    ),
                ),
                (
                    "scenario",
                    models.TextField(
                        blank=True,
                        help_text="Tình huống cụ thể của cuộc hội thoại",
                        verbose_name="Kịch bản",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang diễn ra"),
                            ("completed", "Hoàn thành"),
                            ("abandoned", "Bỏ dở"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "total_messages",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tổng số tin nhắn"
                    ),
                ),
                (
                    "total_duration_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tổng thời gian (giây)"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-5 sao",
                        null=True,
                        verbose_name="Đánh giá",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Nhận xét của người dùng về phiên luyện tập",
                        verbose_name="Phản hồi",
                    ),
                ),
                (
                    "ai_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Đánh giá tự động từ AI về kỹ năng giao tiếp",
                        verbose_name="Nhận xét từ AI",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Điểm đánh giá từ AI (0-100)",
                        null=True,
                        verbose_name="Điểm số",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Bắt đầu lúc"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kết thúc lúc"
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="conversations.persona",
                        verbose_name="Persona",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiên luyện tập",
                "verbose_name_plural": "Phiên luyện tập",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Người dùng"),
                            ("assistant", "Phụ huynh (AI)"),
                            ("system", "Hệ thống"),
                        ],
                        max_length=20,
                        verbose_name="Vai trò",
                    ),
                ),
                ("content", models.TextField(verbose_name="Nội dung")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Văn bản"),
                            ("voice", "Giọng nói"),
                            ("image", "Hình ảnh"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Loại tin nhắn",
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Link file audio nếu là tin nhắn voice",
                        verbose_name="URL audio",
                    ),
                ),
                (
                    "audio_duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Thời lượng audio (giây)"
                    ),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Số tokens AI đã sử dụng cho tin nhắn này",
                        verbose_name="Tokens sử dụng",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Thứ tự tin nhắn trong session",
                        verbose_name="Thứ tự",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian gửi"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="conversations.session",
                        verbose_name="Phiên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tin nhắn",
                "verbose_name_plural": "Tin nhắn",
                "ordering": ["session", "order", "created_at"],
            },
        ),
    ]
